name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    uses: wetransform/gha-workflows/.github/workflows/dockerfile-build.yml@1e60dcabbcf6acccf458c4626baaef1db63f9a8a # v4.1.3
    with:
      image: wetransform/postfix
      tag: pr
